### PR TITLE
Solve the problem of insufficient off-heap memory allocation during consumption.

### PR DESCRIPTION
**Pull request by mingyifei**
Reason: MessageConvertUtils.entryToIndexMessage and MessageConvertUtils.entryToAmqpBody called ByteBuf.retain(),
but did not call release.

### CODE REVIEW

**Comment by mingyifei** [comment]
@gaoran10  hi, help code review.

**Comment by mingyifei** [comment]
I have used rabbitmq perf test to complete, the problem has been resolved.

**Review by gaoran10 — COMMENTED** [review]
Nice work, could we release the data in the methods `MessageConvertUtils#entryToAmqpBody` and `MessageConvertUtils#entryToIndexMessage`?

I'm not sure why we need to retain the ByteBuf in these methods.

**Comment by mingyifei** [comment]
> Nice work, could we release the data in the methods `MessageConvertUtils#entryToAmqpBody` and `MessageConvertUtils#entryToIndexMessage`?
> 
> I'm not sure why we need to retain the ByteBuf in these methods.

You can delete retain or add release, retain() is more asynchronous use scenario, and synchronous scenario feels that you only need to use the head and tail once.

**Comment by mingyifei** [comment]
@gaoran10  
image
Throwing an exception in the middle may also cause a leak of off-heap memory, which is released and moved to finally.

**Review by gaoran10 — APPROVED** [review]
LGTM

**Pull request merged**
